name: build and publish a snapshot

on:
  push:
    branches:
      - master
      - 'snapshot/*'
      - 'kotlin-*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

env:
  BINTRAY_USER: ${{ secrets.bintray_user }}
  BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
  BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}


jobs:
  build-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest] # [macOS-latest, windows-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.265'
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup gradle.properties
        run: mv .github/conf/gradle.${{ matrix.os }} gradle.properties
      - name: Check
        run: ./gradlew check
        shell: bash
      - name: Upload
        run: ./gradlew hostOnlyPublish -PsnapshotNumber=${{ github.run_number }} -PgitRef=${{ github.ref }} --stacktrace
        shell: bash
      - name: Discard
        if: ${{ failure() || cancelled() }}
        run: ./gradlew postBintrayDiscard -PsnapshotNumber=${{ github.run_number }} -PgitRef=${{ github.ref }}
        shell: bash

  build-upload-publish:
    needs: build-upload
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.265'
      - name: Setup Android SDK dir
        run: echo sdk.dir=$ANDROID_HOME > local.properties
      - name: install default NDK for AGP
        run: $ANDROID_HOME/tools/bin/sdkmanager "ndk;21.0.6113669"
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup gradle.properties
        run: mv .github/conf/gradle.ubuntu-latest gradle.properties
      - name: Check
        run: ./gradlew check
        shell: bash
      - name: Upload
        run: ./gradlew publish -PsnapshotNumber=${{ github.run_number }} -PgitRef=${{ github.ref }} --stacktrace
        shell: bash
      - name: Discard
        if: ${{ failure() || cancelled() }}
        run: ./gradlew postBintrayDiscard -PsnapshotNumber=${{ github.run_number }} -PgitRef=${{ github.ref }}
        shell: bash
      - name: Publish
        run: ./gradlew postBintrayPublish -PsnapshotNumber=${{ github.run_number }} -PgitRef=${{ github.ref }}
        shell: bash
