name: test

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'

jobs:
  build-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] # [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Cached Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Cached Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.265'
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Android SDK dir
        if: matrix.os == 'ubuntu-latest'
        run: echo sdk.dir=$ANDROID_HOME > local.properties
      - name: install default NDK for AGP
        if: matrix.os == 'ubuntu-latest'
        run: $ANDROID_HOME/tools/bin/sdkmanager "ndk;21.0.6113669"
      - name: Setup gradle.properties
        run: mv .github/conf/gradle.${{ matrix.os }} gradle.properties
      - name: Check
        run: ./gradlew check
        shell: bash
